name: docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install sphinx dependencies
      run: |
        pip install -r requirements/docs.txt
    - name: Run sphinx-build
      run: |
        cd docs
        sphinx-build -b html source _build
    - name: Create artifact of the html output
      uses: actions/upload-artifact@v2
      with:
        name: DocumentationHTML
        path: docs/_build/
